from . import dz_tax_bracket
from . import dz_social_config
from . import dz_family_config
from . import dz_seniority_config
from . import dz_overtime_rate
from . import dz_transport_config
from . import dz_employee_dependent
from . import hr_employee
from . import hr_payslip_report
from . import dz_payroll_config
from . import hr_payslip
